### ISSUE TITLE
Beta tester issue

### ISSUE THREAD

**Issue by bonzibuddy801** [nepphhh/arrasio#20]
[13.168]: 213.67.46.184,::ffff:10.10.10.53,::ffff:10.10.10.225 is trying to connect...

[13.169]: [INFO] New socket opened with 

[13.334]: [INFO] A socket was verified with the token: 

[13.334]: 

[13.334]: Clients: 1

[13.529]: [INFO]  joined the game! Players: 1

[34.302]: [INFO] User undefined disconnected!

[34.302]: [INFO] Socket closed. Views: 0. Clients: 0.

/app/arrasio/src/server/server.js:2330

            health: this.health.display(),

                                ^

TypeError: this.health.display is not a function

at Entity.camera (/app/arrasio/src/server/server.js:2330:33)

at Entity.takeSelfie (/app/arrasio/src/server/server.js:2547:55)

at entitiesliveloop (/app/arrasio/src/server/server.js:4798:20)

at entities.forEach.e (/app/arrasio/src/server/server.js:4824:35)

    at Array.forEach (<anonymous>)

at Timeout.gameloop [as _onTimeout] (/app/arrasio/src/server/server.js:4824:22)

    at ontimeout (timers.js:498:11)

    at tryOnTimeout (timers.js:323:5)

    at Timer.listOnTimeout (timers.js:290:5)

[21:06:39] [nodemon] app crashed - waiting for file changes before starting...

**Comment by 321tuan** [comment]
reset please
